### PR TITLE
Split words before searching

### LINKED ISSUE #194: Members search function doesn't function intuitively
The search function does not allow for search functionality such as searching for "\<firstname\> \<lastname\>".
The functionality for this should be examined and preferably redesigned to include the option for searching a combination of these two columns. If possible and useful, it could be nice to provide some abstraction for the selection of columns, so that this functionality is also available in other use cases.

### PR DESCRIPTION
**Pull request by Matthijsy**
### Summary
This PR splits every search term and will search for it on every field. This makes it possible to search on first name and last name in the same query

Fixes #194

### CODE REVIEW

**Review by wilco375 — APPROVED** [review]
Looks good

**Comment by DrumsnChocolate** [comment]
was this ever actually merged into staging?

**Comment by wilco375** [comment]
Looks like it was closed without merging for some reason. @Matthijsy ?

**Comment by Matthijsy** [comment]
Yes this did not work, had to implement it differently

**Pull request closed without merging**
