### PR TITLE
Updating Ruby to 3.1.2 

### PR DESCRIPTION
**Pull request by lodewiges**
updating ruby to 3.1.2 this is a clone off the branch that was made by renovate. However the original got lost due to a merging issue and I was unable to recover it so I made a new one.

### CODE REVIEW

**Comment by DrumsnChocolate** [comment]
Did we not already do this in #299?

**Comment by DrumsnChocolate** [comment]
What happened?

**Comment by DrumsnChocolate** [comment]
How did you construct this branch now? Did you think of simply reverting https://github.com/csvalpha/amber-api/commit/120d37c450bcca03a9fa9bb38c807edbeb54ebf0 ? Because I think that's all it takes

**Comment by lodewiges** [comment]
> How did you construct this branch now? Did you think of simply reverting [120d37c](https://github.com/csvalpha/amber-api/commit/120d37c450bcca03a9fa9bb38c807edbeb54ebf0) ? That is: reverting the revert of the ruby update. In other words, reapplying the reverted commit. Because I think that's all it takes

is that possible, i was not aware that you could revert a revert

**Comment by lodewiges** [comment]
> What happened?

299 failed due to the codecov token issue that is fixed now

**Comment by lodewiges** [comment]
> Did we not already do this in #299?

yes

**Comment by DrumsnChocolate** [comment]
> > How did you construct this branch now? Did you think of simply reverting [120d37c](https://github.com/csvalpha/amber-api/commit/120d37c450bcca03a9fa9bb38c807edbeb54ebf0) ? That is: reverting the revert of the ruby update. In other words, reapplying the reverted commit. Because I think that's all it takes
> 
> i was not aware that you could revert a revert. 

Well, think like this: everything happens in the form of commits. So what does reverting do? You guessed it: create a new commit, with opposing changes to the commit you are reverting. So what does a revert of a reversion of a commit do? Create another commit.

See https://stackoverflow.com/a/29975312 for more info

**Comment by lodewiges** [comment]
i revert the revert so everything should be alright now. i will close this PR

**Pull request closed without merging**
